### ISSUE TITLE
Not can begin to work issue

### ISSUE THREAD

**Issue by Kristinita** [rubikonx9/SublimeRegexExplainTip#2]
### Summary

I can not begin to use SublimeRegexExplainTip.
### Expected behavior

![SRETScreen](https://github.com/rubikonx9/SublimeRegexExplainTip/raw/master/screenshots/1.PNG)
### Actual behavior

<del>
    key evt: alt+r
    command: regexexplaintip
    Traceback (most recent call last):
      File "./python3.3/subprocess.py", line 1104, in _execute_child
    FileNotFoundError: [WinError 2] Не удается найти указанный файл
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "E:\Sublime Text 3\sublime_plugin.py", line 818, in run_
        return self.run(edit)
      File "RegexExplainTip in E:\Sublime Text 3\Data\Installed Packages\RegexExplainTip.sublime-package", line 326, in run
      File "RegexExplainTip in E:\Sublime Text 3\Data\Installed Packages\RegexExplainTip.sublime-package", line 103, in get_explanation
      File "./python3.3/subprocess.py", line 819, in __init__
      File "./python3.3/subprocess.py", line 1110, in _execute_child
    FileNotFoundError: [WinError 2] Не удается найти указанный файл

</del>

---

---

Now I reboot my computer and I can get no this error. But I still can not begin to work RegexExplainTip.

![RegexExplainTip](http://i.imgur.com/OBOmGQs.gif)
1. If in my regex only ASCII symbols, after run command: regexexplaintip I see only scrollbar. I can get no stack trace.
2. If in my regular expression not only ASCII symbols, but Cyrillic symbols too I get stack trace:

``` python
    key evt: alt+r
    command: regexexplaintip
    Traceback (most recent call last):
      File "E:\Sublime Text 3\sublime_plugin.py", line 818, in run_
        return self.run(edit)
      File "RegexExplainTip in E:\Sublime Text 3\Data\Installed Packages\RegexExplainTip.sublime-package", line 326, in run
      File "RegexExplainTip in E:\Sublime Text 3\Data\Installed Packages\RegexExplainTip.sublime-package", line 105, in get_explanation
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 249: invalid continuation byte
```
### Steps to reproduce

I install StrawberryPerl via [Chocolatey](https://chocolatey.org/packages/StrawberryPerl) → I install module:

```
E:\Киролайна>cpanm  YAPE::Regex::Explain
--> Working on YAPE::Regex::Explain
Fetching http://www.cpan.org/authors/id/G/GS/GSULLIVAN/YAPE-Regex-Explain-4.01.tar.gz ... OK
Configuring YAPE-Regex-Explain-4.01 ... OK
==> Found dependencies: YAPE::Regex
--> Working on YAPE::Regex
Fetching http://www.cpan.org/authors/id/G/GS/GSULLIVAN/YAPE-Regex-4.00.tar.gz ... OK
Configuring YAPE-Regex-4.00 ... OK
Building and testing YAPE-Regex-4.00 ... OK
Successfully installed YAPE-Regex-4.00
Building and testing YAPE-Regex-Explain-4.01 ... OK
Successfully installed YAPE-Regex-Explain-4.01
2 distributions installed
```

I install SublimeRegexExplainTip via Package Control → I select any text → <kbd>Alt+R</kbd> → I get stack trace.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by Kristinita** [comment]
@rubikonx9 , I update issue.

**Comment by rubikonx9** [comment]
Hello,
Thanks for info.
Sorry for late answer. I am currently on holiday, and have limited access. I will investigate this issue on Monday. Sorry for inconvenience.

**Comment by rubikonx9** [comment]
Hello,

Could you check it with revision 5a96c3cbfe33185278ff549d0bcda78ffa35e863?
I've corrected UTF-8 handling a bit, and I've added more proper error message logging.
Hopefully it will help, either by fixing the issue or providing more details.

**Comment by Kristinita** [comment]
@rubikonx9 , release?

**Comment by Kristinita** [comment]
@rubikonx9 , I download SublimeRegexExplainTip 2016.10.12 version manually → now I constantly get stack trace in console:

``` python
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 199, in create_text_commands
    cmds.append(class_(view))
  File "RegexExplainTip in E:\Sublime Text 3\Data\Installed Packages\SublimeRegexExplainTip.sublime-package", line 74, in __init__
  File "RegexExplainTip in E:\Sublime Text 3\Data\Installed Packages\SublimeRegexExplainTip.sublime-package", line 82, in load_css
  File "E:\Sublime Text 3\sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

Moreover, the plugin SublimeREPL and some default commands of Sublime Text not worked for me, if SublimeRegexExplainTip 2016.10.12 is enabled. 

Thanks.

**Comment by rubikonx9** [comment]
This is disturbing. It doesn't seem to be related at all to what I've changed.
Anyway, I made a new release (version 0.9.1). Please upgrade / reinstall and let me know if anything changes.

**Comment by Kristinita** [comment]
Thank you very much! In 0.9.1 version plugin works for me.
